export const FETCH_EXERCISES_TOPICS_START = 'FETCH_EXERCISES_TOPICS_START'
export const FETCH_EXERCISES_TOPICS_SUCCESS = 'FETCH_EXERCISES_TOPICS_SUCCESS'
export const FETCH_EXERCISES_TOPICS_ERROR = 'FETCH_EXERCISES_TOPICS_ERROR'