export const FETCH_EXERCISES_TOPICS_START = 'FETCH_EXERCISES_TOPICS_START'
export const FETCH_EXERCISES_TOPICS_SUCCESS = 'FETCH_EXERCISES_TOPICS_SUCCESS'
export const FETCH_EXERCISES_TOPICS_ERROR = 'FETCH_EXERCISES_TOPICS_ERROR'

export const FETCH_EXERCISES_START = 'FETCH_EXERCISES_START'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCH_EXERCISES_ERROR = 'FETCH_EXERCISES_ERROR'

export const CLICK_EVENT_ANSWER_SUCCESS = 'CLICK_EVENT_ANSWER_SUCCESS'
export const CLICK_EVENT_ANSWER_IS_FINISHED = 'CLICK_EVENT_ANSWER_IS_FINISHED'
export const CLICK_EVENT_ANSWER_NEXT = 'CLICK_EVENT_ANSWER_NEXT'
export const CLICK_EVENT_ANSWER_ERROR = 'CLICK_EVENT_ANSWER_ERROR'

export const CLICK_EVENT_REPEAT_EXERCISE = 'CLICK_EVENT_REPEAT_EXERCISE'