export const FETCH_EXERCISES_TOPICS_START = 'FETCH_EXERCISES_TOPICS_START'
export const FETCH_EXERCISES_TOPICS_SUCCESS = 'FETCH_EXERCISES_TOPICS_SUCCESS'
export const FETCH_EXERCISES_TOPICS_ERROR = 'FETCH_EXERCISES_TOPICS_ERROR'

export const FETCH_EXERCISES_START = 'FETCH_EXERCISES_START'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCH_EXERCISES_ERROR = 'FETCH_EXERCISES_ERROR'

export const CLICK_EVENT_ANSWER_SUCCESS = 'CLICK_EVENT_ANSWER_SUCCESS'
export const CLICK_EVENT_ANSWER_IS_FINISHED = 'CLICK_EVENT_ANSWER_IS_FINISHED'
export const CLICK_EVENT_ANSWER_NEXT = 'CLICK_EVENT_ANSWER_NEXT'
export const CLICK_EVENT_ANSWER_ERROR = 'CLICK_EVENT_ANSWER_ERROR'

export const CLICK_EVENT_REPEAT_EXERCISE = 'CLICK_EVENT_REPEAT_EXERCISE'

export const ADD_IN_LIST_EXERCISE = 'ADD_IN_LIST_EXERCISE'
export const ADD_IN_DB_LIST_EXERCISES = 'ADD_IN_DB_LIST_EXERCISES'
export const ADD_IN_DB_LIST_EXERCISES_ERROR = 'ADD_IN_DB_LIST_EXERCISES_ERROR'
export const VALIDATION_CHANGE_INPUT = 'VALIDATION_CHANGE_INPUT'
export const CHANGE_EVENT_THEME_INPUT = 'CHANGE_EVENT_THEME_INPUT'
export const CHANGE_SELECT_CORRECT_ANSWER = 'CHANGE_SELECT_CORRECT_ANSWER'

export const LOGIN_OR_REGISTRATION = 'LOGIN_OR_REGISTRATION'
export const AUTO_LOGOUT = 'AUTO_LOGOUT'